import "./globals.css";
import type { Metadata } from "next";

import { WalletProvider } from "@/contexts/WalletProvide";
import { Apolloprovider } from "@/apolloProvider";
import { Provider } from "./provider";
import { Web3Provider } from "@/contexts/Web3Provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased `}
      >
        <Web3Provider>
          <Provider>
            <WalletProvider>
              <Apolloprovider>
                {children}
              </Apolloprovider>
            </WalletProvider>
          </Provider>
        </Web3Provider>
      </body>
    </html>
  );
}

